[[redirects]]
  from = "https://codewithahsan.dev/ng-book"
  to = "https://www.amazon.com/Angular-Cookbook-recipes-enterprise-scale-development-dp-1838989439/dp/1838989439/"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/youtube"
  to = "https://youtube.com/c/CodewithAhsan"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/gde"
  to = "https://developers.google.com/community/experts/directory/profile/profile-muhammad-ahsan-ayaz"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/instagram"
  to = "https://instagram.com/muhd.ahsanayaz"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/facebook"
  to = "https://facebook.com/muhd.ahsanayaz"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/tiktok"
  to = "https://tiktok.com/@muhd.ahsanayaz"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/resume"
  to = "https://linkedin.com/in/ahsanayaz"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/linkedin"
  to = "https://linkedin.com/in/ahsanayaz"
  status = 301
  force = true
[[redirects]]
  from = "https://codewithahsan.dev/twitter"
  to = "https://twitter.com/codewith_ahsan"
  status = 301
  force = true

[[redirects]]
  from = "https://codewithahsan.dev/author"
  to = "https://www.amazon.com/~/e/B098TSDC9B"
  status = 301
  force = true
