name: "Build"

on:
  pull_request:
    branches: [main]
    types: [open]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: yarn
      - name: "Build"
        run: yarn build
