name: "Deploy"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: yarn
      - name: "Deploy"
        run: yarn deploy
