name: Publish to GH-PAGES
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [15.x]
    env:
      USER_NAME: github-actions
      USER_EMAIL: github-actions@users.noreply.github.com
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup GIT
        run: |
          git config user.name ${{ env.USER_NAME }}
          git config user.email ${{ env.USER_EMAIL }}
      - name: Reset GH_PAGES branch to MAIN
        run: |
          git fetch origin
          git checkout gh-pages
          git reset --hard origin/main
      - name: Push any changes to GH_PAGES branch
        run: |
          git add .
          git commit -m "chore(action): push any changes from main"
          git push origin gh-pages
